<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "videothumbs"
 *
 * Auto generated by Extension Builder 2020-04-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Video Thumbs',
    'description' => 'Proof of concept to have thumbnails of local video files',
    'category' => 'example',
    'author' => 'Robert von Hackwitz',
    'author_email' => 'hostmaster@usb.it',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
